# Site settings
title: Docs FR DemocracyOS
email: contact@democracyos.eu
description: > # this means to ignore newlines until "baseurl:"
  Site de documentation pour la version fran√ßaise de DemocracyOS.
baseurl: "/docs-fr/" # the subpath of your site, e.g. /blog/
url: "http:/democracyos.eu/docs-fr" # the base hostname & protocol for your site
twitter_username: democracyos_fr
github_username:  democracy-os-fr

# Build settings
markdown: kramdown

# paginate: 5

author: Virgile

# gems: [jekyll-paginate]
